# Generated by Django 3.2.7 on 2021-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
